"""Add obligacje table and user FK, names

Revision ID: 483864d1e854
Revises: 
Create Date: 2025-09-22 12:14:41.483483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '483864d1e854'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obligacje', schema=None) as batch_op:
        batch_op.alter_column('csv_content',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.drop_constraint(batch_op.f('fk_user_obligacje'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'obligacje', ['obligacje_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_obligacje'), 'obligacje', ['obligacje_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('uq_user_email'), ['email'], unique=True)

    with op.batch_alter_table('obligacje', schema=None) as batch_op:
        batch_op.alter_column('csv_content',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    # ### end Alembic commands ###
