"""Nowa struktura z agregacja

Revision ID: e806b1001040
Revises: 
Create Date: 2025-12-12 22:02:55.269487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e806b1001040'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bond_definitions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('isin', sa.VARCHAR(length=12), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('issuer', sa.VARCHAR(length=100), nullable=False),
    sa.Column('series', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bond_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('emission_date', sa.Date(), nullable=True),
    sa.Column('coupon_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('nominal_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bond_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bond_definitions_bond_type'), ['bond_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_bond_definitions_isin'), ['isin'], unique=True)
        batch_op.create_index(batch_op.f('ix_bond_definitions_issuer'), ['issuer'], unique=False)
        batch_op.create_index(batch_op.f('ix_bond_definitions_maturity_date'), ['maturity_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bond_definitions_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('portfolios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cash_balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
    sa.Column('bond_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('purchase_price', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('transaction_reference', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('current_value', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['bond_definition_id'], ['bond_definitions.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'bond_definition_id', name='uq_holding_portfolio_bond')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_bond_definition_id'), ['bond_definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holdings_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holdings_purchase_date'), ['purchase_date'], unique=False)

    op.create_table('portfolio_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_value', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('cash_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('bond_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'date', name='uq_portfolio_history_date')
    )
    with op.batch_alter_table('portfolio_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_history_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_history_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
    sa.Column('bond_definition_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', 'MATURITY', 'COUPON', name='transaction_type_enum'), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('fees', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('transaction_reference', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bond_definition_id'], ['bond_definitions.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_portfolio_date', ['portfolio_id', 'transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_bond_definition_id'), ['bond_definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_reference'), ['transaction_reference'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_reference'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_bond_definition_id'))
        batch_op.drop_index('idx_portfolio_date')

    op.drop_table('transactions')
    with op.batch_alter_table('portfolio_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_history_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_history_date'))

    op.drop_table('portfolio_history')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_purchase_date'))
        batch_op.drop_index(batch_op.f('ix_holdings_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_holdings_bond_definition_id'))

    op.drop_table('holdings')
    op.drop_table('user_settings')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_user_id'))

    op.drop_table('portfolios')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('bond_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bond_definitions_name'))
        batch_op.drop_index(batch_op.f('ix_bond_definitions_maturity_date'))
        batch_op.drop_index(batch_op.f('ix_bond_definitions_issuer'))
        batch_op.drop_index(batch_op.f('ix_bond_definitions_isin'))
        batch_op.drop_index(batch_op.f('ix_bond_definitions_bond_type'))

    op.drop_table('bond_definitions')
    # ### end Alembic commands ###
